version: '3'
############################################################################################
# READ ME : This file is meant to run the containers locally and have the backend running
# in you IDE. ETCD is enable.
# 
# Will be Aggregated with : .\lib\killrvideo-docker-common\docker-compose.yaml
############################################################################################
services:
  
  dse-config:
    image: killrvideo/killrvideo-dse-config:1.2.2
    environment:
      KILLRVIDEO_DOCKER_IP: $KILLRVIDEO_DOCKER_IP
      KILLRVIDEO_DSE_EXTERNAL_IP: $KILLRVIDEO_DSE_EXTERNAL_IP
      KILLRVIDEO_CASSANDRA_REPLICATION: $KILLRVIDEO_CASSANDRA_REPLICATION
      KILLRVIDEO_GRAPH_REPLICATION: $KILLRVIDEO_GRAPH_REPLICATION
    depends_on:
    - dse
      
  # ----------------------------------
  # Killrvideo
  # ----------------------------------
  
  # Web UI (looking backend in ETCD)
  web:
    image: killrvideo/killrvideo-web:1.2.8
    ports:
    - "3000:3000"
    depends_on:
    - dse
    - etcd
    environment:
      SERVICE_3000_NAME: web
      KILLRVIDEO_ETCD: "etcd:2379"
      KILLRVIDEO_DSE_USERNAME: $KILLRVIDEO_DSE_USERNAME
      KILLRVIDEO_DSE_PASSWORD: $KILLRVIDEO_DSE_PASSWORD
      KILLRVIDEO_CASSANDRA_REPLICATION: $KILLRVIDEO_CASSANDRA_REPLICATION
      KILLRVIDEO_LOGGING_LEVEL: $KILLRVIDEO_LOGGING_LEVEL

  # Look for video in youtube and push to backend (ETCD required)
  generator:
    image: killrvideo/killrvideo-generator:1.2.5
    depends_on:
    - dse
    - etcd
    environment:
      KILLRVIDEO_ETCD: "etcd:2379"
      KILLRVIDEO_DSE_USERNAME: $KILLRVIDEO_DSE_USERNAME
      KILLRVIDEO_DSE_PASSWORD: $KILLRVIDEO_DSE_PASSWORD
      NODE_ENV: $NODE_ENV
      KILLRVIDEO_CASSANDRA_REPLICATION: $KILLRVIDEO_CASSANDRA_REPLICATION
      KILLRVIDEO_LOGGING_LEVEL: $KILLRVIDEO_LOGGING_LEVEL
   
  # Java Backend services    
  #server:
  #  image: killrvideo/killrvideo-services-java:latest
  #  ports:
  #  - "8899:8899"
  #  depends_on:
  #  - etcd
  #  - web
  #  environment:
  #    KILLRVIDEO_HOST_IP: $KILLRVIDEO_HOST_IP
  #    KILLRVIDEO_DOCKER_IP: $KILLRVIDEO_DOCKER_IP
  #    KILLRVIDEO_DSE_USERNAME: $KILLRVIDEO_DSE_USERNAME
  #    KILLRVIDEO_DSE_PASSWORD: $KILLRVIDEO_DSE_PASSWORD
  #    KILLRVIDEO_ENABLE_SSL: $KILLRVIDEO_ENABLE_SSL
  #  volumes:
  #    - "../../cassandra.cert:/usr/src/app/cassandra.cert"  
