version: '3'
# Other services are specified in .\lib\killrvideo-docker-common\docker-compose.yaml
services:
 
  # Ensure consistency in Kafka World
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  # Start the Kafka Engine for Killrvideo
  kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.75.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-kv-videoCreation:1:1,topic-kv-userCreation:1:1,topic-kv-videoRating:1:1"
    ports:
    - 9092:9092

  # We UI for Kafka, brosing topics
  kafkahq:
    image: tchiotludo/kafkahq
    environment:
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "10.0.75.1:9092"
    ports:
      - "8080:8080"
    depends_on:
      - kafka