version: '3'
services:

  # ---------------------------------- 
  # DataStax Enterprise Database
  # ----------------------------------
  dse: 
    image: datastax/dse-server:6.7.2
    command: [ -s -g ] # Run with Search and Graph capabilities enabled
    ports: # Exposes ports to be available. Kompose tool needs that to create a k8s service and make backend available for other services.
      - "9042:9042" # Exposes DSE port
      - "8983:8983" # Exposes DSE Search port
      - "8182:8182" # Exposes DSE Graph port
    environment:
      DS_LICENSE: accept # Accept licence on start
      DC: DC1
      JVM_EXTRA_OPTS: -Xmx1g -Xms1g
      NUM_TOKENS: 32
    cap_add:
      - IPC_LOCK # Allow DSE to lock memory with mlock
    depends_on:
    #  - opscenter  
    ulimits:
      memlock: -1
  
  # ----------------------------------     
  # DataStax Studio
  # ----------------------------------
  studio:
    image: datastax/dse-studio:6.7.0
    ports:
     - "9091:9091"
    depends_on:
     - dse
    environment:
      SERVICE_9091_NAME: studio
      DS_LICENSE: accept
    volumes:
       - "/tmp/docker/studio-notebooks:/var/lib/datastax-studio"  
   
  # ----------------------------------
  # OpsCenter
  # ----------------------------------
  #opscenter:
  #  image: "datastax/dse-opscenter:6.7.0"
  #  ports:
  #    - 8888:8888
  #  environment:
  #    - DS_LICENSE=accept
  
  # ----------------------------------
  # Killrvideo
  # ----------------------------------
  
  # ----------------------------------
  # Web Interface (No ETCD)
  # ----------------------------------
  web: 
    image: killrvideo/killrvideo-web:3.0.0
    ports:
      - "3000:3000" # Exposes port to be available externally
    depends_on:
      - backend # Needs Backend to be running
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging
    labels:
      kompose.service.type: nodeport # Adds a label for Kompose to expose service externally

  # ----------------------------------
  # Backend exposing GRPC services
  # ----------------------------------
  backend:
    # JAVA IMPLEMENTATION
    image: killrvideo/killrvideo-java:latest
    # Exposes port to be available. Kompose tool needs that to create a k8s service and make backend available for other services.
    ports:
      - "50101:50101" 
    depends_on:
      - dse 
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug
      KILLRVIDEO_DSE_USERNAME: $KILLRVIDEO_DSE_USERNAME
      KILLRVIDEO_DSE_PASSWORD: $KILLRVIDEO_DSE_PASSWORD
      KILLRVIDEO_ENABLE_SSL: $KILLRVIDEO_ENABLE_SSL
    volumes:
      - "../../cassandra.cert:/usr/src/app/cassandra.cert"     

  dse-config: # One-Time Bootstrap Container, configures DSE to have required keyspaces etc.
    image: killrvideo/killrvideo-dse-config:3.0.0
    environment:
      KILLRVIDEO_SERVICE_DISCOVERY_DISABLED: 'true' # Backward Compatibility Requirement
    depends_on:
      - dse # Needs DSE to be running
    restart: on-failure # Kompose needs that to create dse-config as a pod, not a deployment. DSE-Config deployment is not needed as we run it only once.

  generator:
    image: killrvideo/killrvideo-generator:3.0.0
    depends_on:
      - backend
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug
      
